### ISSUE TITLE
_tkinter.TclError: no display name and no $DISPLAY environment variable

### ISSUE THREAD

**Issue by mbarnig** [MitchellProductions/Coqui-TTS-GUI-solution#1]
I tried to run the Coqui-TTS-GUI, without success. I don't know how to set the display name and the $DISPLAY environment variable. Here are the error messages :   
![coqui-tts-gui](https://user-images.githubusercontent.com/1360633/113436962-07f21980-93e6-11eb-8776-da50e3e7d448.jpg)
Thank you for your help.

**Comment by smaybius** [comment]
It requires a desktop environment, assuming you're on WSL 2: https://gist.github.com/Ta180m/e1471413f62e3ed94e72001d42e77e22

**Comment by mbarnig** [comment]
Thank you for your quick answer and for the link to the WSL2 GNOME Desktop.
With this tool and and with the help of the Shogan.tech tutorial [WSL2 GUI X-Server Using VcXsrv](https://www.shogan.co.uk/how-tos/wsl2-gui-x-server-using-vcxsrv/) I was able to install and run the Coqui-TTS-GUI. 
![coqui-tts-gui-display](https://user-images.githubusercontent.com/1360633/113474648-70d2a380-9471-11eb-8231-301b1434b6b2.jpg)
A very useful tool to progress with my TTS projects related to the luxembourgish language.
I will now close this topic. Kind regards.
